#!/usr/bin/env node

// Red tests for scripts/verify-release-identity.mjs.
//
// The baseline is not a hand-written fixture. It is produced by running the
// repository's own `changeset version` over the real committed changesets, so
// the accepted state is literally what Changesets computes — if the guard and
// Changesets ever disagree about what a release looks like, this test fails
// rather than the release.
//
// Every other case takes that genuine release state and breaks exactly one
// property, asserting the guard rejects it. Without the baseline, a guard that
// rejected everything would pass all of them.

import { mkdtempSync, rmSync, cpSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const guard = join(repoRoot, "scripts", "verify-release-identity.mjs");
const changesetsBin = join(repoRoot, "node_modules", "@changesets", "cli", "bin.js");

if (!existsSync(changesetsBin)) {
  console.error(
    `verify-release-identity.test: @changesets/cli is not installed at ${changesetsBin}.\n` +
      "  The baseline is generated by the real versioning tool; it is not faked when the tool is absent.\n" +
      "  Run `pnpm install` first.",
  );
  process.exit(1);
}

// ---------------------------------------------------------------- baseline
// A genuine post-`changeset version` tree: tracked files only, then versioned.
const released = mkdtempSync(join(tmpdir(), "wsjson-release-base-"));
{
  const archive = spawnSync("git", ["archive", "HEAD"], { cwd: repoRoot, encoding: "buffer", maxBuffer: 1 << 28 });
  if (archive.status !== 0) throw new Error(`git archive failed: ${archive.stderr}`);
  const extract = spawnSync("tar", ["-x", "-C", released], { input: archive.stdout });
  if (extract.status !== 0) throw new Error(`tar extract failed: ${extract.stderr}`);

  const versioned = spawnSync("node", [changesetsBin, "version"], { cwd: released, encoding: "utf8" });
  if (versioned.status !== 0) {
    throw new Error(`changeset version failed in the scratch tree:\n${versioned.stdout}${versioned.stderr}`);
  }
}

const releasedVersion = JSON.parse(readFileSync(join(released, "packages/spec/package.json"), "utf8")).version;
const releasedTag = `standard-v${releasedVersion}`;
console.log(`baseline: changeset version computed ${releasedVersion} from the committed changesets\n`);

function withReleaseTree(mutate, tag = releasedTag) {
  const dir = mkdtempSync(join(tmpdir(), "wsjson-release-"));
  try {
    cpSync(released, dir, { recursive: true });
    mutate(dir);
    const args = [guard];
    if (tag !== null) args.push("--tag", tag);
    const result = spawnSync("node", args, {
      cwd: dir,
      encoding: "utf8",
      env: { ...process.env, WORKSPACEJSON_RELEASE_ROOT: dir, WORKSPACEJSON_RELEASE_TAG: "", GITHUB_REF_TYPE: "" },
    });
    return { status: result.status, out: `${result.stdout}${result.stderr}` };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const patchJson = (dir, rel, fn) => {
  const p = join(dir, rel);
  const d = JSON.parse(readFileSync(p, "utf8"));
  fn(d);
  writeFileSync(p, JSON.stringify(d, null, 2));
};

const cases = [];
const accept = (name, mutate, tag) => cases.push({ name, expectReject: false, needle: null, mutate, tag });
const reject = (name, needle, mutate, tag) => cases.push({ name, expectReject: true, needle, mutate, tag });

accept("baseline: the real `changeset version` output is ACCEPTED at its own tag", () => {});

// ------------------------------------------------------------- tag identity
reject(
  "a repository-wide version tag is refused",
  "repository-wide version tag",
  () => {},
  `v${releasedVersion}`,
);

reject(
  "a tag missing the package scope is refused",
  "does not match",
  () => {},
  `standard-${releasedVersion}`,
);

reject(
  "no tag at all is refused rather than skipped",
  "no release tag supplied",
  () => {},
  null,
);

reject(
  "a tag naming a version nobody computed is refused",
  "the tag must follow it",
  () => {},
  "standard-v9.9.9",
);

// --------------------------------------------------------- fixed-group shape
reject(
  "a foreign package in the fixed group is refused",
  "does not publish",
  (d) => patchJson(d, ".changeset/config.json", (c) => { c.fixed = [["@workspacejson/spec", "@workspacejson/rules", "agents-audit"]]; }),
);

reject(
  "a fixed group missing a member is refused",
  "omits @workspacejson/rules",
  (d) => patchJson(d, ".changeset/config.json", (c) => { c.fixed = [["@workspacejson/spec"]]; }),
);

reject(
  "a second fixed group leaves the release version ambiguous",
  "fixed group(s)",
  (d) => patchJson(d, ".changeset/config.json", (c) => { c.fixed = [["@workspacejson/spec"], ["@workspacejson/rules"]]; }),
);

// --------------------------------------------------------------- lockstep
reject(
  "a hand-edited sibling version breaks lockstep",
  "disagree on version",
  (d) => patchJson(d, "packages/rules/package.json", (m) => { m.version = "9.9.9"; }),
);

reject(
  "a private group member cannot be published",
  "marked private",
  (d) => patchJson(d, "packages/rules/package.json", (m) => { m.private = true; }),
);

reject(
  "a floating intra-group range is refused",
  "intra-workspace link or the exact group version",
  (d) => patchJson(d, "packages/rules/package.json", (m) => { m.dependencies["@workspacejson/spec"] = "^0.5.0"; }),
);

// The inverse: an exact pin is a legitimate alternative to `workspace:` and must
// NOT be reported. Without this, a guard rejecting every range would pass above.
accept("an exact intra-group pin is ACCEPTED", (d) =>
  patchJson(d, "packages/rules/package.json", (m) => { m.dependencies["@workspacejson/spec"] = releasedVersion; }));

// ------------------------------------------------------- Changesets output
reject(
  "a changeset surviving the release commit is refused",
  "still pending at this ref",
  (d) => writeFileSync(
    join(d, ".changeset", "late-arrival.md"),
    '---\n"@workspacejson/spec": patch\n---\n\nLanded after the version bump.\n',
  ),
);

reject(
  "a missing generated changelog entry is refused",
  "was not versioned by Changesets",
  (d) => {
    const p = join(d, "packages/spec/CHANGELOG.md");
    writeFileSync(p, readFileSync(p, "utf8").replace(`## ${releasedVersion}`, "## 0.0.0-not-this-release"));
  },
);

// ---------------------------------------------------------------- run
let passed = 0;
let failed = 0;
for (const c of cases) {
  const { status, out } = withReleaseTree(c.mutate, c.tag === undefined ? releasedTag : c.tag);
  const rejected = status !== 0;
  let ok = rejected === c.expectReject;
  if (ok && c.expectReject && c.needle) ok = out.includes(c.needle);

  if (ok) {
    passed++;
    console.log(`PASS  ${c.expectReject ? "refused — " : ""}${c.name}`);
  } else {
    failed++;
    console.log(`FAIL  ${c.name}`);
    console.log(`        expected ${c.expectReject ? `refusal mentioning ${JSON.stringify(c.needle)}` : "acceptance"}, got exit ${status}`);
    console.log(out.split("\n").map((l) => `        ${l}`).join("\n"));
  }
}

rmSync(released, { recursive: true, force: true });

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed === 0 ? 0 : 1);
